### ISSUE TITLE
indieProject Checkpoint 2 ready

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/indieProject#5]
@pawaitemadisoncollege  
I believe my checkpoint 2 is all set
My database is up and running 
Both user and review have DAOs with full crud (still need to add and implement the generic dao but I don't think that was required for this checkpoint)
Log4J is implemented

**Comment by pawaitemadisoncollege** [comment]
Hi @jbjohnson2! Great job hitting checkpoint 2 from the DAO/Hibernate/Log4J standpoint! Completing the work each week in your project set you up really well here! I poked around in your repo a bit and did not notice anything I'm concerned about related to best practices at this point (you already highlighted that the generic dao needs to be implemented). 

- [x] Can you add an image of your ERD so that I can review and provide any feedback (if this is here already and I overlooked it, please let me know). If you don't have a preferred way to create the erd, you can generate it out of the database view in IntelliJ. I think the sequence is right click on the db, then diagrams. I realize I should have been more clear about including this for this CP. 
- [x] You've been doing a good job updating your time log and plan as you complete work. Did you find a good solution for time-tracking?  
- [x] If you haven't reviewed and updated your plan recently for the final 8 weeks, this would be a good time to do that, since you now have all the learning on new topics need for the project (or will have in the next few days). 

I'm going to mark this as "not yet" in blackboard mostly as a reminder to myself that I need to review the ERD yet.

**Comment by jbjohnson2** [comment]
Hi Paula, I took a screenshot of my ERD but it does not look as I expected it to. I added a foreign key to connect the review table and the users table(id/user_id) and one to connect the reviews table to the state park table (park/park_name). But the ERD only shows an arrow from the reviews to the users table . Do you know what I've done wrong? I will add a screenshot of the ERD and my foreign keys. 

![ERD](https://github.com/jbjohnson2/indieProject/assets/90119350/487214e0-61b9-4b41-a7ab-955a1b60b3c9)
![foreignkeys](https://github.com/jbjohnson2/indieProject/assets/90119350/864b8085-c142-411f-9aa4-8f6dd9cee49c)

@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @jbjohnson2 hmmm. I am not sure, but it *could* be due to not having an id column on the state_park table. Generally it's a best practice to have a unique identifier that isn't used for anything else as the pk (as far as I know hibernate needs this in order to work properly, too).  Are you up for trying that?
