### ISSUE TITLE
checkpoint 3 ready for review

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/indieProject#6]
@pawaitemadisoncollege 
I have my project deployed to aws and have a jsp that displays data from the database(results.jsp).
I have kept my time log updated and have updated my project plan.
I implemented authentication with cognito although I am having an issue when I connect my  app in elastic beanstalk with cognito that I need to figure out.  It says my certificate is invalid and my site is not secure.  I have tried getting new certificate, and copying and pasting the information again, but that has not work. I posted about it on slack. 
I am currently using the cognito branch in my project

**Comment by pawaitemadisoncollege** [comment]
Hi @jbjohnson2!  Wow! You did a nice job with the styling - home page looks fantastic! I tested out the functionality a bit and reviewed your repo - you hit CP3 which sets you up really well for a strong finish! Good use of branching when adding in that cognito functionality. 

I noticed a few things related to best practices that I wanted to point out. I am guessing _many_ of these are on your radar already, but I also use these issues to track how the project improves over time, so I'm going to "jot" them down here. Some of this may be nitpicky which is an indication of the quality of your work so far (no major concerns).

- [x] implement the generic dao to eliminate duplication in the entity-specific daos (unit tests for entity-days will remain, they will just use the generic dao instead). Once converted over, remove the entity-specific daos.
- [x] This might be a V2+ task: as I was looking at your site and erd: the db would be more normalized with a table for campground (since some parks have more than 1) and probably then a table for the sites, which would have campground on the table.  I think this is best left for a future version. Keeping a list of things like this would show anyone looking at your repo that you realize the areas for improvement and have a plan for them. 
- [x] Sign up and login buttons could toggle to logout if the user is already logged in. 
- [x] Consider using the jquery datatable for added sorting and searching functionality on the reviews table. 
- [x] Can you use the jstl c:import tag rather than the directive (you will still need at least one directive to bring in the taglib and that is ok) https://github.com/jbjohnson2/indieProject/blob/1c934ea5de56cecce7db67fbc87eaa839be15877/src/main/webapp/browseSites.jsp#L5
- [ ] Consider adding an error.jsp page (and to your web.xml) - that can show in the event of a 404, 505. Seems like opportunity for a fun "camping mishap" error page -you know how some sites have fun pages for a 404?
